### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by balcsida**
I've tested it locally and everything worked as expected, even Webpack 4.1

### CODE REVIEW

**Comment by HaNdTriX** [comment]
Awesome thanks a lot! 🙏

**Comment by HaNdTriX** [comment]
Sorry that was a bit to quick. 
I tested it locally and there are currently some issues.

* https://github.com/Milanzor/webpack-watched-glob-entries-plugin/issues/1

**Comment by balcsida** [comment]
Thanks! Will check that if I can fix/help with that issue.

**Comment by balcsida** [comment]
Just a question: if I switch back to Webpack 3.x in my PR it should work, right?
Also, what issues did you encounter, so I can test it on my side as well?

**Comment by HaNdTriX** [comment]
Thanks a lot for helping out!

I created a new PR regarding Webpack 4. 
Some external Webpack Plugins need to update first. 

https://github.com/HaNdTriX/webextension-toolbox/pull/13

**Comment by HaNdTriX** [comment]
Just released Version 0.2.0 

* https://github.com/HaNdTriX/webextension-toolbox/releases/tag/v0.2.0
* https://www.npmjs.com/package/webextension-toolbox

**Comment by balcsida** [comment]
Awesome, many thanks!

**Pull request merged**
