### PR TITLE
Update dependencies (again)

### PR DESCRIPTION
**Pull request by balcsida**
Sorry, I think I did it correctly this time :|

### CODE REVIEW

**Comment by HaNdTriX** [comment]
I am currently on vacation. Since this is not critical I‘ll take a look at this, as soon as possible. Thanks a lot for your contributions!

**Comment by balcsida** [comment]
Sure thing, have a nice vacation! :)

**Comment by HaNdTriX** [comment]
fyi: https://greenkeeper.io/

**Comment by balcsida** [comment]
Yep, that's what I wanted to recommend as well 😄 
I think it requires permissions so only you can set that up.

**Comment by HaNdTriX** [comment]
I‘ll add it as soon we have proper tests and CI servers in place.

**Pull request merged**
